### ISSUE TITLE
Issue with salesforce scheduled processes/cron

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#2423]
Every 5 minutes the following is logged in the drush logs.

```
 [error]  InvalidArgumentException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Url.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  InvalidArgumentException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Url.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  InvalidArgumentException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Url.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  InvalidArgumentException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 291 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Url.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  Drupal\Core\Entity\EntityStorageException: The URI 'TBD' is invalid. You must use a valid URI scheme. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 811 of /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php). 
 [error]  TypeError: basename(): Argument #1 ($path) must be of type string, Drupal\Core\Url given in basename() (line 330 of /mnt/www/html/bostond8/docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php) #0 /mnt/www/html/bostond8/docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php(330): basename()
#1 [internal function]: Drupal\node_buildinghousing\EventSubscriber\SalesforceBuildingHousingUpdateSubscriber->pullPresave()
#2 /mnt/www/html/bostond8/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#3 /mnt/www/html/bostond8/docroot/modules/contrib/salesforce/modules/salesforce_mapping/src/Entity/MappedObject.php(587): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#4 /mnt/www/html/bostond8/docroot/modules/contrib/salesforce/modules/salesforce_pull/src/Plugin/QueueWorker/PullBase.php(216): Drupal\salesforce_mapping\Entity\MappedObject->pull()
#5 /mnt/www/html/bostond8/docroot/modules/contrib/salesforce/modules/salesforce_pull/src/Plugin/QueueWorker/PullBase.php(126): Drupal\salesforce_pull\Plugin\QueueWorker\PullBase->updateEntity()
#6 /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Cron.php(182): Drupal\salesforce_pull\Plugin\QueueWorker\PullBase->processItem()
#7 /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/Cron.php(147): Drupal\Core\Cron->processQueues()
#8 /mnt/www/html/bostond8/docroot/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\Core\Cron->run()
#9 /mnt/www/html/bostond8/vendor/drush/drush/src/Drupal/Commands/core/DrupalCommands.php(76): Drupal\Core\ProxyClass\Cron->run()
#10 [internal function]: Drush\Drupal\Commands\core\DrupalCommands->cron()
#11 /mnt/www/html/bostond8/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array()
#12 /mnt/www/html/bostond8/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#13 /mnt/www/html/bostond8/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#14 /mnt/www/html/bostond8/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process()
#15 /mnt/www/html/bostond8/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#16 /mnt/www/html/bostond8/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
#17 /mnt/www/html/bostond8/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /mnt/www/html/bostond8/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /mnt/www/html/bostond8/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run()
#20 /mnt/www/html/bostond8/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun()
#21 /mnt/www/html/bostond8/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run()
#22 /mnt/www/html/bostond8/vendor/drush/drush/drush(4): require('...')
#23 /mnt/www/html/bostond8/vendor/bin/drush(117): include('...')
#24 {main}. 
TypeError: basename(): Argument #1 ($path) must be of type string, Drupal\Core\Url given in basename() (line 330 of /mnt/www/html/bostond8/docroot/modules/custom/bos_content/modules/node_buildinghousing/src/EventSubscriber/SalesforceBuildingHousingUpdateSubscriber.php).
 [warning] Drush command terminated abnormally.

```

**Comment by davidrkupton** [comment]
@padora-cob This is a new one for you to take a look at.
